#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os, sys
import subprocess
import argparse


parser = argparse.ArgumentParser( description='Para contenedor ' )
parser.add_argument("contenedor",type=str)
args = parser.parse_args()


comando = 'docker stop  '+ args.contenedor
print "Parando contenedor"
print comando
os.system(comando)
