#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os, sys
import subprocess
import argparse


parser = argparse.ArgumentParser( description='Acceder a un contenedor' )
parser.add_argument("contenedor",type=str)
args = parser.parse_args()

comando = 'docker attach  ' + args.contenedor
print "Accediendo al contendor contenedor"
print comando
os.system(comando)
